// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// redSVDwrap
List redSVDwrap(const Eigen::MappedSparseMatrix<double> A, const int num);
RcppExport SEXP RRedsvd_redSVDwrap(SEXP ASEXP, SEXP numSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double> >::type A(ASEXP);
    Rcpp::traits::input_parameter< const int >::type num(numSEXP);
    __result = Rcpp::wrap(redSVDwrap(A, num));
    return __result;
END_RCPP
}
// redSymwrap
List redSymwrap(const Eigen::MappedSparseMatrix<double> A, const int num);
RcppExport SEXP RRedsvd_redSymwrap(SEXP ASEXP, SEXP numSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double> >::type A(ASEXP);
    Rcpp::traits::input_parameter< const int >::type num(numSEXP);
    __result = Rcpp::wrap(redSymwrap(A, num));
    return __result;
END_RCPP
}
// redPCAwrap
List redPCAwrap(const Eigen::MappedSparseMatrix<double> A, const int num);
RcppExport SEXP RRedsvd_redPCAwrap(SEXP ASEXP, SEXP numSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double> >::type A(ASEXP);
    Rcpp::traits::input_parameter< const int >::type num(numSEXP);
    __result = Rcpp::wrap(redPCAwrap(A, num));
    return __result;
END_RCPP
}
