# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

redSVDwrap <- function(A, num) {
    .Call('RRedsvd_redSVDwrap', PACKAGE = 'RRedsvd', A, num)
}

redSymwrap <- function(A, num) {
    .Call('RRedsvd_redSymwrap', PACKAGE = 'RRedsvd', A, num)
}

redPCAwrap <- function(A, num) {
    .Call('RRedsvd_redPCAwrap', PACKAGE = 'RRedsvd', A, num)
}

